### ISSUE TITLE
Orders: Current day order not displayed in the All orders tab

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1705]
When testing this [PR](https://github.com/woocommerce/woocommerce-android/pull/1699), I noticed that a new order created is not being displayed in the `All` orders tab but is still visible in the `Processing` tab.

<img width="300" src="https://user-images.githubusercontent.com/22608780/70793062-832e5700-1dc0-11ea-9f80-ee4d665a723a.gif">

#### To reproduce:
- Create a new order and wait for the order notification.
- Click on the notification and you will be redirected to the Order detail screen.
- Click back from this screen and notice that in the `All` orders tab, this order is not visible.
- Click on the `Processing` tab and notice that the order is visible under `Today` section.

**Comment by AmandaRiu** [comment]
@anitaa1990 This should've been fixed by #1699 . Can you retest?

**Comment by anitaa1990** [comment]
Hey @AmandaRiu I tested this after merging PR #1699. I tested again by pulling changes from `develop` and still facing the same issue by following the same steps listed in the issue description.

<img width="300" src="https://user-images.githubusercontent.com/22608780/70885254-5bc4cd80-1ffe-11ea-8075-5e02a341fe27.gif">

**Comment by AmandaRiu** [comment]
@AmandaRiu Keeping this in the 3.3 release milestone. Fix will need to target the `release/3.3` branch.

**Comment by AmandaRiu** [comment]
Fixed in #1724 Closing ticket.
