### ISSUE TITLE
Orders: Extra bottom divider on order list search

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3251]
**Describe the bug**

As @Garance91540 reported:

When selecting search on the order list, there seems to be an extra bottom divider on the search bar, could we remove it?

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/100894969-f723ac80-34b4-11eb-8236-e6517cfb3ad2.png" width="300px">

**Mobile Environment**
Please include:
- Device: 
- Android version: 
- WooCommerce Android version: 5.6-rc-1

**Comment by shiki** [comment]
@nbradbury Is this related to #3254?

**Comment by nbradbury** [comment]
@shiki This was fixed in #3274.

**Comment by Garance91540** [comment]
Hi @nbradbury ! I'm still seeing the extra divider in the search bar on my device (testing 5.8) https://d.pr/i/tgP86F

**Comment by malinajirka** [comment]
Automated reproduction check/comment.

I was able to reproduce this on June 15, 2026 using WooCommerce Android 24.9-rc-3 on `Medium_Phone_API_35` (`emulator-5558`).

Steps checked:
1. Logged into the provided staging site via Google SSO.
2. Opened the Orders tab.
3. Tapped the Orders search action.

Result: the search toolbar still shows a light-gray horizontal divider/underline beneath the search field, matching the reported visual issue. This appears to still be relevant.

**Comment by malinajirka** [comment]
Automated migration comment.

This reproducible Android bug has been moved to Linear for triage and follow-up: https://linear.app/a8c/issue/WOOMOB-3231/android-orders-extra-bottom-divider-on-order-list-search

Closing this GitHub issue to avoid duplicate tracking. The Linear issue contains the bug description, reproduction steps, expected behavior, and automated audit result.
